# Generated by Django 6.0.7 on 2026-07-20 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gitar', models.CharField(max_length=150)),
                ('brand_model', models.CharField(max_length=150)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=12)),
                ('biaya_tambahan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_modal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_masuk', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_terjual', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terjual', 'Terjual')], default='Tersedia', max_length=20)),
            ],
        ),
    ]
