# Generated by Django 6.0.7 on 2026-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Alat Musik')),
                ('description', models.TextField(verbose_name='Deskripsi Produk')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga (Rp)')),
                ('condition', models.CharField(choices=[('baru', 'Baru (Brand New)'), ('mulus', 'Bekas Mulus (Mint)'), ('bagus', 'Bekas Bagus (Good Condition)'), ('butuh_perbaikan', 'Butuh Perbaikan (Fair/Broken)')], default='baru', max_length=20, verbose_name='Kondisi')),
                ('location', models.CharField(default='Batam', max_length=100, verbose_name='Lokasi Pengiriman')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Sudah Terjual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Daftar Produk',
                'ordering': ['-created_at'],
            },
        ),
    ]
